services:
  - type: web
    name: hero-wiki-backend
    env: java
    rootDir: backend
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/herowiki-0.0.1-SNAPSHOT.jar
    healthCheckPath: /api/heroes
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_FRONTEND_URL
        sync: false
      - key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID
        sync: false
      - key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET
        sync: false
      - key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID
        sync: false
      - key: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET
        sync: false
      - key: SERVER_SERVLET_SESSION_COOKIE_SAME_SITE
        value: none
      - key: SERVER_SERVLET_SESSION_COOKIE_SECURE
        value: "true"
